// 从 @mlc/schema 统一导出所有类型
export type {
  ComponentSchema,
  ComponentStyle,
  EditorConfig,
  ComponentLibrary,
  ComponentFramework,
  CanvasSchema,
  CanvasConfig,
  GridConfig,
  PropFieldType,
  SelectOption,
  PropFieldConfig,
  PropConfig,
  PropGroup,
  EventActionType,
  EventTrigger,
  EventBinding,
  EventDeclaration,
  EventActionConfig,
  NavigateConfig,
  ShowMessageConfig,
  SetStateConfig,
  CallApiConfig,
  CustomCodeConfig,
  // 数据绑定类型
  VariableScope,
  VariableType,
  VariableDefinition,
  DataSourceType,
  HttpMethod,
  ApiDataSourceConfig,
  StaticDataSourceConfig,
  DataSourceDefinition,
  BindingType,
  PropertyBinding,
  ComponentBindings,
  ExpressionContext,
  CanvasDataConfig,
} from '@mlc/schema';

export { ToolMode } from '@mlc/schema';

// 重导出校验和辅助方法
export {
  validateCanvas,
  validateComponent,
  createEventBinding,
  createDefaultActionConfig,
  addEventToComponent,
  removeEventFromComponent,
  updateEventInComponent,
  // 数据绑定辅助方法
  generateVariableId,
  createVariable,
  getDefaultValueForType,
  generateDataSourceId,
  createStaticDataSource,
  createApiDataSource,
  createVariableDataSource,
  createStaticBinding,
  createExpressionBinding,
  createVariableBinding,
  createDataSourceBinding,
  evaluateExpression,
  validateExpression,
  extractVariablesFromExpression,
  resolveBinding,
  getValueByPath,
  setValueByPath,
  createEmptyContext,
  isExpressionBinding,
  isBindingExpression,
  extractExpression,
  wrapExpression,
} from '@mlc/schema';
